/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTestBackendRouteImport } from './routes/api/test-backend'
import { Route as ApiAnalyzeBillRouteImport } from './routes/api/analyze-bill'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestBackendRoute = ApiTestBackendRouteImport.update({
  id: '/api/test-backend',
  path: '/api/test-backend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeBillRoute = ApiAnalyzeBillRouteImport.update({
  id: '/api/analyze-bill',
  path: '/api/analyze-bill',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/analyze-bill': typeof ApiAnalyzeBillRoute
  '/api/test-backend': typeof ApiTestBackendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/analyze-bill': typeof ApiAnalyzeBillRoute
  '/api/test-backend': typeof ApiTestBackendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/analyze-bill': typeof ApiAnalyzeBillRoute
  '/api/test-backend': typeof ApiTestBackendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/analyze-bill' | '/api/test-backend'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/analyze-bill' | '/api/test-backend'
  id: '__root__' | '/' | '/api/analyze-bill' | '/api/test-backend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAnalyzeBillRoute: typeof ApiAnalyzeBillRoute
  ApiTestBackendRoute: typeof ApiTestBackendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-backend': {
      id: '/api/test-backend'
      path: '/api/test-backend'
      fullPath: '/api/test-backend'
      preLoaderRoute: typeof ApiTestBackendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-bill': {
      id: '/api/analyze-bill'
      path: '/api/analyze-bill'
      fullPath: '/api/analyze-bill'
      preLoaderRoute: typeof ApiAnalyzeBillRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAnalyzeBillRoute: ApiAnalyzeBillRoute,
  ApiTestBackendRoute: ApiTestBackendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
